version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mongodb:
    image: mongo:8
    container_name: mongo_db
    env_file:
      - ./backend/.env
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DB}
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: nest_backend
    depends_on:
      - postgres
      - mongodb
    env_file: /backend/.env
    ports:
      - "3000:3000"
    command: npm run start:dev
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  mongo-data: