version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: shop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: